### ISSUE TITLE
Improve meshing speed

### ISSUE THREAD

**Issue by Inspirateur** [Inspirateur/riverbed#16]
Current meshing breakdown (data for 62-sized chunks with no LODs)
- __~1ms__: build mesh data buffer (undo the palette compression + include neighbor) 
-  __~4.7ms__: use [bonsairobo/block-mesh-rs](https://github.com/bonsairobo/block-mesh-rs) to mesh the chunk

For a total of nearly __6ms__ per chunk on my machine, which is quite slow, especially for the big render distance we need ! 

### This can be greatly improved with Binary Greedy Meshing

If you don't know about it, here's [Tantan's video](https://www.youtube.com/watch?v=qnGoGq7DWMc) on the topic; but basically the strategy is to pack voxel occupancy data (binary) into 64 bits numbers and perform bitwise operations to find quad groups much faster.

Benchmarking [Tantan's implementation](https://github.com/TanTanDev/binary_greedy_mesher_demo) of BGM in Rust gives me a meshing time of ~130μs for a 32-sized chunk (with [AO](https://0fps.net/2013/07/03/ambient-occlusion-for-minecraft-like-worlds/)),  
we can expect it to be around **~800μs** for 62-sized chunks.

[cgerikj/binary-greedy-meshing](https://github.com/cgerikj/binary-greedy-meshing) in C is the best BGM impl I know of and they report speeds of **50μs to 200μs** per 62-sized chunk !  
(They also support AO)

This would be about **~60x times faster** than our current meshing.

The issue is that Tantan's impl is more of a demo than a crate (it packs a whole voxel engine with it), it's also not fully optimized, and the other impl is in C, which I'd rather not use ! 

### We need a Rust Binary Greedy Meshing crate on par with the C version

We can get inspiration from both the C version and Tantan's implementation. I think it would be very helpful for the voxel Rust ecosystem, with the following specs:
- support 64 sized (neighbors included) chunks
- bake AO (common need in every voxel game)
- support YXZ data layout (which we use)

### TODO
- [x] port C version of BGM to Rust
- [x] use BGM to mesh chunks
- [x] pad the chunks to store neighbor info
- [x] add LOD with BGM

**Comment by Inspirateur** [comment]
So i've started to work on it here https://github.com/Inspirateur/binary-greedy-meshing
The port from the C crate is written, no idea if it's correct yet. I'll need to test it in the game.

**Comment by Inspirateur** [comment]
I think I'm going to wait until we get instancing (#5) to use BGM, because its output is designed for instancing and if we don't use it we need to do a bunch of tricky transformations to the output that we wouldn't need to do otherwise. I think the port is ready though, there might be some bugs but we can catch them later :)

**Comment by Inspirateur** [comment]
Another important phase to optimize is the neighbor information filling that currently takes ~1ms. 
Here we can either adopt the common strategy of storing the neighbor information in the chunk directly, remove this step entirely at the expense of terrain generation and modification (would be worth it overall), or try to find a way to optimize it but it is not trivial...

**Comment by Inspirateur** [comment]
So I ended up switching to BGM before we have instancing because I couldn't wait for the juicy performance gains and after doing some benchmarking it seems the meshing is now x10 faster than before. 

It's not the x60 improvement I predicted because the reported numbers of **50μs to 200μs** per chunks assume that we maintain an opacity mask that takes like 300μs to compute. But still, a 10x improvement is fantastic!

Big things are still missing from my port of BGM such as support for LODs and transparency (which are not in the original lib), they will take some time to implement, but it's a good step forward.

**Comment by Inspirateur** [comment]
Ok I've added back LODs but an unexpected side effect of having a chunk size of 62 is that they break beyond size 2 (because 62 is only a multiple of 2 and 31). 

That being said it's honestly not that bad, because we'll get good performance even with LOD 2 and if we need more we can implement some kind of quad cutting logic to make sure the quad don't go beyond their chunks.

Also, the new LOD system is better because it prefers taking solid blocks instead of air, which removes the problem of floating trees that we had with the previous version !

Now I just need to update the neighbor info of chunks and I'll consider this issue closed.

**Comment by Inspirateur** [comment]
Ok I'm removing the task of updating neighbor info because it is kind of optional (if you set all the neighbors to AIR), and will only be needed when we're bottlenecked by the amount of quads (which we aren't for now, the bottleneck is drawcalls until we get instancing).

And with that, this issue is done ! Meshing speed ended up ~x7 times faster than before (less than anticipated because of transparency costing a lot), which is a big win !
